// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKxSVmxCo7s_XJWi8fUhkCwlY1gzhAbqQ',
    appId: '1:99655930652:web:3a7dbbd5a45ac789bce0d9',
    messagingSenderId: '99655930652',
    projectId: 'demoinviration',
    authDomain: 'demoinviration.firebaseapp.com',
    storageBucket: 'demoinviration.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXjD8KgWxoR089w6rG7yW5ZGogsj010tc',
    appId: '1:99655930652:android:edad8c5a45bd0fe4bce0d9',
    messagingSenderId: '99655930652',
    projectId: 'demoinviration',
    storageBucket: 'demoinviration.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAh76n811JHh9E6LWs199mHn4n2n6Ruk8',
    appId: '1:99655930652:ios:a8fe70ef8f6451f1bce0d9',
    messagingSenderId: '99655930652',
    projectId: 'demoinviration',
    storageBucket: 'demoinviration.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAh76n811JHh9E6LWs199mHn4n2n6Ruk8',
    appId: '1:99655930652:ios:a8fe70ef8f6451f1bce0d9',
    messagingSenderId: '99655930652',
    projectId: 'demoinviration',
    storageBucket: 'demoinviration.appspot.com',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKxSVmxCo7s_XJWi8fUhkCwlY1gzhAbqQ',
    appId: '1:99655930652:web:8ef7915931d832c7bce0d9',
    messagingSenderId: '99655930652',
    projectId: 'demoinviration',
    authDomain: 'demoinviration.firebaseapp.com',
    storageBucket: 'demoinviration.appspot.com',
  );

}